# Get input data from database
import cx_Oracle
import sqlalchemy as sqla
import os
import pandas as pd
import numpy as np

conn = cx_Oracle.connect('xhq/xhq2mes@akuas952.office.graphiteelectrodes.net/mes301')
cur = conn.cursor()
#cur.execute('select * from vw_mes_total')

sql_st = """
SELECT RECV_PIECE_ID, RECV_GREEN_LENGTH, PI_MEASLENGTH_MM, FIN_LENGTH_IN_MM, RECV_GREEN_DIAMETER_H AS GREEN_DIAMETER,FIN_LENGTH_OUT_MM,FIN_TIME_EXIT_S3,
(RECV_GREEN_LENGTH-PI_MEASLENGTH_MM) AS BAKESHRINKAGE,
(PI_MEASLENGTH_MM-FIN_LENGTH_IN_MM) AS GRAPHSHRINKAGE,
RECV_COKE,
RECV_AOS_CLUSTER,
BAK_FIRING_RECIPE,
GRA_SPIN_FORMULANUMBER,
RECV_NOMINAL_LENGTH,
RECV_NOMINAL_OD
FROM vw_mes_total
WHERE
(RECV_GREEN_LENGTH-PI_MEASLENGTH_MM)>0 AND (RECV_GREEN_LENGTH-PI_MEASLENGTH_MM)<80  AND 
(PI_MEASLENGTH_MM-FIN_LENGTH_IN_MM)>0 AND (PI_MEASLENGTH_MM-FIN_LENGTH_IN_MM)<80  AND 
RECV_GREEN_LENGTH>0 AND PI_MEASLENGTH_MM>0 AND FIN_LENGTH_IN_MM>0 AND RECV_GREEN_DIAMETER_H >0 AND
FIN_MACHINED_ENDDATE > '09-09-2023'
ORDER BY FIN_MACHINED_ENDDATE DESC  """

df_input2 = pd.read_sql_query(sql_st, con=conn)



